# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AWS_REGION : eu-west-2

# Permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:     
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      # Clone the repository
      - name: Git clone the repository
        uses: actions/checkout@v4.1.1
      
      # Link the pipeline with the AWS Account containing the IAM role
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          # Use IAM role ARN stored as GitHub secret
          role-to-assume: ${{secrets.IAM_ROLE_CICD_ARN}}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # Prove the identifier
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.5
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Validate
        run: terraform validate
  
      - name: Terraform Plan
        run: terraform plan -out=tf

      - name: Terraform Apply
        run: terraform apply --auto-approve
